### ISSUE TITLE
Консистентность оборачивания ошибок

### ISSUE THREAD

**Issue by gosolivs** [evrone/go-service-template#25]
В методах `Shutdown` у сервера и клиента ошибки оборачиваются с помощью `fmt.Errorf`, а в остальных местах `pkg/rabbitmq` с помощью `errors.Wrap` из сторонней либы. Так задумано?

https://github.com/evrone/go-service-template/blob/46ae5d6ed690206e6d1b8d13b1bb6e52c2cf76bb/pkg/rabbitmq/rmq_rpc/client/client.go#L235
https://github.com/evrone/go-service-template/blob/46ae5d6ed690206e6d1b8d13b1bb6e52c2cf76bb/pkg/rabbitmq/rmq_rpc/server/server.go#L151

**Comment by neprja** [comment]
Спасибо за замечание!
Должно всегда оборачиваться с помощью `errors.Wrap`. Исправлю.
